### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by yanimeziani** [haydenbleasel/next-forge#363] opened 2024-12-16 23:14 UTC
Currently, next-forge doesn't include built-in localization support in its template, which means developers need to manually implement internationalization features.

**Comment by haydenbleasel** [comment] 2024-12-17 01:31
Thanks @yanimeziani, this looks like a duplicate of #297 so I'm going to go ahead and mark it as such 👍 Keen to hear your thoughts on the main issue!

**Closed** 2024-12-17 01:31 UTC
Labels: duplicate, enhancement
