### ISSUE TITLE
Error when deploying in Vercel

### ISSUE THREAD

**Issue by OsoThevenin** [haydenbleasel/next-forge#247] opened 2024-11-15 13:47 UTC
**Describe the bug**
I am deploying a clean version of next-forge in Vercel, and it fails due to env variables wrongly configured.
The latest commit in my git is the result of running the init script.

**next-forge version**
I am using version 2.14.15

**To Reproduce**
1. Create a new project with `npx next-forge@latest init my-project`
2. Fill all the env variables in .env.local files.
3. Check that build command on the root of the project works (`pnpm build`)
4. Create a new repo in GitHub and push the changes.
5. Deploy the app project in Vercel. Turbo is detected.
6. Change the root of the project and choose `/apps/app`
7. Add the env variables and deploy

I also tried to create a new project through the Vercel Marketplace but got the same result.
Also tried to modify the build commands (see screenshot) because the default was `turbo build`
Edit: Also executed the `vercel link` to try to discard and tried to made `NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL` optional in case it was failing due to the first build.

**Expected behavior**
Expected to compile successfully

**Screenshots**
Screenshot of the project configuration (app):
<img width="915" alt="image" src="https://github.com/user-attachments/assets/9471fa80-32f7-4e15-b74f-4e4228982ab6">

Screenshot of the error:
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/335f666f-4bea-4a7b-9175-8941f52f7c7b">

**Desktop (please complete the following information):**
 - OS: macOS (latest)
 - Browser Chrome

**Comment by haydenbleasel** [comment] 2024-11-15 17:02
@OsoThevenin It should be added by Vercel on deploy: https://vercel.com/docs/projects/environment-variables/framework-environment-variables#NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL. Weird that it's not. I'll look into it.

**Comment by haydenbleasel** [comment] 2024-11-16 10:35
@coderreco Ah yes now I remember fixing that recently 😂 

@OsoThevenin I'll ask the Vercel team about that error directly.

**Comment by coderreco** [comment] 2024-11-16 10:47
> @coderreco Ah yes now I remember fixing that recently 😂
> 
> @OsoThevenin I'll ask the Vercel team about that error directly.

I actually did also experience the same error as originally reported. If I delete the `NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL` it will throw an error and stop the build. Have to add manually. Confirmed on both `app` and `web` 🤷‍♂️

**Comment by haydenbleasel** [comment] 2024-11-16 23:14
@OsoThevenin @coderreco are you folks pushing "production" Vercel deploys? I.e. is the branch you're pushing marked as the production branch in Vercel deployments?

**Comment by OsoThevenin** [comment] 2024-11-17 09:18
> @OsoThevenin @coderreco are you folks pushing "production" Vercel deploys? I.e. is the branch you're pushing marked as the production branch in Vercel deployments?

Yes, all 3 checks

**Comment by Gomah** [comment] 2024-11-21 10:10
I faced the same issue, I think it's due to the [zod validation in the env package](https://github.com/haydenbleasel/next-forge/blob/main/packages/env/index.ts#L48), it's incorrect:

```
// Added by Vercel
NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL: z.string().min(1).url()
```

The `NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL` variable is a bit misleading (maybe Vercel should have named it `NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_DOMAIN` ?) as it returns [the domain without the protocol](https://vercel.com/docs/projects/environment-variables/framework-environment-variables#NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL), so the `.url()` check from zod is likely to fail.

I fixed it by removing `.url()` and adding a prefix helper where `NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL` is called ✌🏻 

Happy to submit a PR & thank you for this awesome template @haydenbleasel 🤚🏻 🇦🇺

**Comment by haydenbleasel** [comment] 2024-11-21 15:59
Great detective work @Gomah! Yes please I'd love a PR 🙏

**Closed** 2024-11-25 15:44 UTC
Labels: bug, needs repro
